apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: terraform
    team: {{ .Values.teamId }}
spec:
  teamId: {{ .Values.teamId }}
  numberOfInstances: {{ .Values.numberOfInstances }}
  postgresql:
    version: "{{ .Values.pgVersion }}"
  volume:
    size: {{ .Values.volumeSize }}
  resources:
    requests:
      cpu: {{ .Values.cpuRequest }}
      memory: {{ .Values.memoryRequest }}
    limits:
      cpu: {{ .Values.cpuLimit }}
      memory: {{ .Values.memoryLimit }}
  sidecars:
    - name: exporter
      image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
      ports:
        - name: metrics
          containerPort: 9187
          protocol: TCP
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
      env:
        - name: DATA_SOURCE_URI
          value: "localhost:5432/postgres?sslmode=disable"
        - name: DATA_SOURCE_USER
          value: postgres
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: "postgres.{{ .Values.clusterName }}.credentials.postgresql.acid.zalan.do"
              key: password
        - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
          value: "true"
