apiVersion: v1
kind: Service
metadata:
  name: sample-app-ts
  namespace: observability
  labels:
    app: sample-app-ts
spec:
  type: ClusterIP
  selector:
    app: sample-app-ts
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
